### PR TITLE
Correctly escape non-unicode regex

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by lahma** [comment]
Something seems to break with these changes.

*  I replaced NuGet reference in `Jint.csproj` with local reference to this branch
* Enabeld unicode tests in `Tests262Test.cs` (search for `unicode`)
* Enabled unicode tests in `Jint.Tests.Tests262\test\skipped.json`  (search for `unicode`)

Observations:

* `Jint.Tests.CommonScripts` has now failing test in babel testing:
   * babel-standalone.js - Line 79828: Invalid regular expression
* `Jint.Tests.Ecma` now has 8 failing tests
  * one example: `Error: #0: var arr = /\u0000/.exec(\u0000); arr[0] === "\u0000". Actual. null`
* `Jint.Tests.Tests262` had 20 failing tests with unicode enabled, now it has 22

**Comment by lahma** [comment]
Looks better now, I still see two test cases failing for old Ecma tests:

* Ecma Chapter 7(sourceFile: ch07/7.8/7.8.5/S7.8.5_A1.1_T1.js)
* Ecma Chapter 7(sourceFile: ch07/7.8/7.8.5/S7.8.5_A2.1_T1.js)

And then the failing ones in new test suite when unicode enabled (the shouldn't be blockers as new tests):

* built-ins\RegExp(sourceFile: built-ins/RegExp/dotall/without-dotall-unicode.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/dotall/without-dotall.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/property-escapes/character-class.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/prototype/Symbol.match/builtin-infer-unicode.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/prototype/Symbol.match/builtin-success-u-return-val-groups.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/prototype/Symbol.match/u-advance-after-empty.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/prototype/Symbol.replace/u-advance-after-empty.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/prototype/Symbol.search/u-lastindex-advance.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/unicode_restricted_brackets.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/unicode_restricted_character_class_escape.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/unicode_restricted_identity_escape.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/unicode_restricted_identity_escape_alpha.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/unicode_restricted_identity_escape_c.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/unicode_restricted_identity_escape_u.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/unicode_restricted_incomple_quantifier.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/unicode_restricted_octal_escape.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/unicode_restricted_quantifiable_assertion.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/character-class-escape-non-whitespace.js)
* built-ins\RegExp(sourceFile: built-ins/RegExp/dotall/with-dotall-unicode.js)

* language\white-space(sourceFile: language/white-space/mongolian-vowel-separator-eval.js)
     * I think this has some changed spec behind it, if I recall right

**Comment by sebastienros** [comment]
I marked some of these explicitly in Jint for now. Some rules are not implemented in esprima, like verifying that `[]{}()` are balances when the `u` flag is set. Will attempt to fix these too. Haven't checked the old Ecma ones yet, thanks.

**Review by lahma — APPROVED** [review]
I'll trust that you know what you are doing ;)

**Pull request merged**
