### PR TITLE
Support class static blocks

### PR DESCRIPTION
**Pull request by jogibear9988**
commit b6ec3c79d317ed0d8d861c72567730a0f723ba3e from esprima-next - parse class "static blocks"

### CODE REVIEW

**Comment by jogibear9988** [comment]
@lahma 
breaking change, it changes list type of class body.
in estree spec it is a or of 3 different types, this is not possible in C#
https://github.com/estree/estree/blob/master/es2022.md#classbody

**Review by lahma — APPROVED** [review]

**Comment by lahma** [comment]
Seems that it has to break compatibility, thanks for this.

**Comment by jogibear9988** [comment]
@lahma 
Should we also change https://github.com/sebastienros/esprima-dotnet/blob/cf68c4db7a3548de83d64d4dc678c446346fd248/src/Esprima/Ast/MethodDefinition.cs#L5
According to definition from EsTree it is derived from Node and not Class Property.
We then need to copy all Properties from ClassProperty

**Comment by lahma** [comment]
I also noticed that currently `PrivateIdentifier` is derived from `Expression` and in spec it's said to be deriving from `Node` maybe these both could be changed? Unless there are even more I haven't noticed yet. With these I think we can either target 2.2 or even 3.0, there's also other cleanup planned later I guess.

**Pull request merged**
