### PR TITLE
Code style/formatting improvements

### PR DESCRIPTION
**Pull request by adams85**

### CODE REVIEW

**Comment by lahma** [comment]
I will be on mobile from now on until Monday,  so harder to check big changes. How does git blame behave after this? I guess every line will be changed?

**Comment by lahma** [comment]
Ignore revs file can help here, but probably after squash merge when hash is known.


https://akrabat.com/ignoring-revisions-with-git-blame/

**Comment by adams85** [comment]
Yeah, it looks like an ignore revs file is the way to go if we want this. Here's another article: https://medium.com/codex/how-to-introduce-a-code-formatter-without-messing-up-git-history-4a16bd074c10

**Review by lahma — APPROVED** [review]
Probably invalidates all current PRs, but a good cleanup.

**Pull request merged**
