### PR TITLE
Fixes a few bugs in parser (#292)

### LINKED ISSUE #292: A few slight parsing bugs
While testing the AST to JS feature, I noticed the following problems with the parser:

1. The statement terminator semicolon in `export default async x => x * x;` is interpreted incorrectly as an `EmptyStatement`.
2. The class declaration
    ```
    class X { async
    f(){} }
    ```
    is parsed as expected (`async` becomes a `PropertyDefinition`). However,
    ```
    class X { async;
    f(){} }
    ```
    results in error, although property definitions are normally terminated by semicolon.
3. `@decorator class X { }` parsed incorrectly as class expression instead of a class declaration.

AST Explorer also verifies that these are actual bugs.

### PR DESCRIPTION
**Pull request by adams85**
Aims to resolve #292. There were more problems around decorators than it looked at first. Hopefully, this would fix them all.

### CODE REVIEW

**Review by lahma — APPROVED** [review]
Thanks for adressing also parsing bugs, help is really needed on this area. Looks good to my eye.

**Comment by lahma** [comment]
Ready to merge?

**Comment by lahma** [comment]
BTW, acorn source code is also a good reference for parsing some constructs, pretty neat code base.

**Comment by adams85** [comment]
Yeah, it's ready.

**Comment by lahma** [comment]
@adams85 hopefully you got an invite as collaborator to this repository and you can do a bit more without us blocking you. 

If  change looks OK to you and not too risky, act like you wish. PR peer review might be good for bigger changes but if people are unavailable, don't hesitate to use your own judgement.

**Comment by adams85** [comment]
I got the invitation, thanks for the confidence!

As a matter of fact, there are still a few things which would be nice to set straight for v3. Now it will definitely be smoother to make those changes.

**Comment by sebastienros** [comment]
Standard process is to not use a fork, just create local task branches, and when a PR is merged the branch is deleted (automatically). If you prefer forks feel free to continue though. I don't.

**Pull request merged**
