### PR TITLE
WIP: Async functions support

### PR DESCRIPTION
**Pull request by codeFather2**
I thought that support for asynchronous functions and expressions would be a good addition to the project. For now tests are failing, because off json dumps format change. I will fix it, for now it's just a WIP PR :)
**TODO** : `await` statements

### CODE REVIEW

**Comment by sebastienros** [comment]
Great to see! Are you following the esprima source code?

**Comment by codeFather2** [comment]
I didn’t look at the original repository when I started to do it, but since it turned out to be quite similar to the original, I will finish writing it off from the original. For some reason I didn’t think to do it right this way.

**Comment by sebastienros** [comment]
This is how the whole parser has been written, almost direct port from js to c#. And it makes it easier for us to apply fixes locally. Including the unit tests.

**Comment by lahma** [comment]
Might help to update failing parse trees with ones from JS esprima master, they have the async attribute included IIRC..

**Comment by lahma** [comment]
I went through the Esprima tree and checked required changes, unfortunately their approach was quite different I was unable to refine without a rewrite. I've created a separate PR which shows the changes required to get tests passing and code conforming to original project style https://github.com/sebastienros/esprima-dotnet/pull/121 . 

@codeFather2 I hope you don't mind I went ahead with this with different approach. It can be tricky to port the features as the documentation is a bit lacking about best practices here.

**Comment by sebastienros** [comment]
@codeFather2 thanks for your effort

**Comment by codeFather2** [comment]
@lahma thank you for your work 👍

**Pull request closed without merging**
