### PR TITLE
Use inheritance instead of interfaces

### PR DESCRIPTION
**Pull request by lahma**
So now that Jint is going to do some heave traversal of AST I decided to look into improving performance in that area. All these empty interfaces have always bothered me and they are never used (even in Jint that does handle almost the full AST). I think the origin has been TypeScript typing in Esprima side where the rules have made sense as TS has all kinds of union types to use, however c# doesn't.

In this PR:

* `INode` is removed, it's basically `Node`, it's faster to access, no interface dispatch
* Removed all interfaces except for IFunction, which ties function expressions and declarations
* everything is basically an `Expression` or `Statement` (which both are `StatementListItem`s)
* sealing AST types
* less allocations in enumeration of children, now using concrete struct enumerator type
* also tweaked NodeList and ArrayList's enumerator to behave like List.Enumerator in BCL

I've already found some logic errors in Jint (non-critical) but the interfaces hid some code paths that were never accessed.

### CODE REVIEW

**Comment by sebastienros** [comment]
Much simpler to read obviously. I see some types got removed, at first I wondered how you would, but they are just conveying type information, and mostly useless. I probably used them to follow the esprima semantics. LGTM.

**Comment by lahma** [comment]
Now performance regressions. AST walk is slightly slower due to enumerator logic but now basically allocation free.

## Esprima.Benchmark.AstTreeWalkBenchmark

| **Diff**|Method|Mean|Error|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------:|-------|-------:|-------:|-------:|-------:|
| Old |VisitChildren|5.588 ms|0.0102 ms|773.4375|0.0000|0.0000|3.09 MB|
| **New** |	| **6.178 ms (+11%)** | **0.0734 ms** | **0.0000 (-100%)** | **0.0000** | **0.0000** | **42 B (-100%)** |


## Esprima.Benchmark.FileParsingBenchmark

| **Diff**|Method|FileName|Mean|Error|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------|-------:|-------|-------:|-------:|-------:|-------:|
| Old |ParseProgram|angular-1.2.5|28.292 ms|0.2144 ms|2343.7500|968.7500|125.0000|13.11 MB|
| **New** |	|	| **27.797 ms (-2%)** | **0.3874 ms** | **2343.7500 (0%)** | **968.7500 (0%)** | **125.0000 (0%)** | **13.11 MB (0%)** |
| Old |ParseProgram|backbone-1.1.0|3.196 ms|0.0158 ms|378.9063|187.5000|0.0000|2.07 MB|
| **New** |	|	| **3.094 ms (-3%)** | **0.0281 ms** | **378.9063 (0%)** | **187.5000 (0%)** | **0.0000** | **2.07 MB (0%)** |
| Old |ParseProgram|jquery-1.9.1|22.534 ms|0.3415 ms|2031.2500|968.7500|125.0000|11.43 MB|
| **New** |	|	| **22.282 ms (-1%)** | **0.3536 ms** | **2031.2500 (0%)** | **968.7500 (0%)** | **125.0000 (0%)** | **11.43 MB (0%)** |
| Old |ParseProgram|jquery.mobile-1.4.2|40.064 ms|0.4953 ms|3230.7692|923.0769|307.6923|17.7 MB|
| **New** |	|	| **39.310 ms (-2%)** | **0.4558 ms** | **3230.7692 (0%)** | **923.0769 (0%)** | **307.6923 (0%)** | **17.7 MB (0%)** |
| Old |ParseProgram|mootools-1.4.5|18.690 ms|0.3704 ms|1718.7500|843.7500|125.0000|9.36 MB|
| **New** |	|	| **18.285 ms (-2%)** | **0.3598 ms** | **1781.2500 (+4%)** | **906.2500 (+7%)** | **156.2500 (+25%)** | **9.36 MB (0%)** |
| Old |ParseProgram|underscore-1.5.2|2.590 ms|0.0095 ms|359.3750|136.7188|0.0000|1.8 MB|
| **New** |	|	| **2.562 ms (-1%)** | **0.0143 ms** | **359.3750 (0%)** | **136.7188 (0%)** | **0.0000** | **1.8 MB (0%)** |
| Old |ParseProgram|yui-3.12.0|16.513 ms|0.3753 ms|1593.7500|781.2500|93.7500|8.56 MB|
| **New** |	|	| **16.383 ms (-1%)** | **0.2377 ms** | **1593.7500 (0%)** | **781.2500 (0%)** | **93.7500 (0%)** | **8.56 MB (0%)** |


## Jint.Benchmark.EvaluationBenchmark

| **Diff**|Method|N|Mean|Error|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------|-------:|-------|-------:|-------:|-------:|-------:|
| Old |ParseProgram|200|5.583 ms|0.0312 ms|1265.6250|0.0000|0.0000|5.07 MB|
| **New** |	|	| **5.550 ms (-1%)** | **0.0438 ms** | **1265.6250 (0%)** | **0.0000** | **0.0000** | **5.07 MB (0%)** |

**Comment by sebastienros** [comment]
Bump https://github.com/sebastienros/esprima-dotnet/blob/dev/src/Esprima/Esprima.csproj#L17 to 2.0.x ?

Then I would create a release/1.x branch to track the previous version, master would then become 2.0.x

Also update the benchmarks table on the readme?

**Comment by lahma** [comment]
Did the version change. How did you get the perf numbers for original Esprima?

**Pull request merged**
