### PR TITLE
Support nullish coalescing

### PR DESCRIPTION
**Pull request by lahma**
https://github.com/jquery/esprima/commit/3515f7e596a351349235517d5435e834c8d395b7

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Comment by sebastienros** [comment]
No test?

**Comment by lahma** [comment]
They run parsing against the 262 test suite like jint with allow list to skip unsupported features, NET version doesn't have this.

**Review by atifaziz — CHANGES_REQUESTED** [review]
This PR upgrades projects to target .NET 5 (silently dropping .NET Core 3.1 that is LTS) , which is an unrelated to its subject (“Support nullish coalescing”) and therefore should be a separate PR.

**Comment by sebastienros** [comment]
@atifaziz I don't think it's dropping anything. Just that the tests and benchmarks use the latest version. The library keeps the current targets.

**Comment by sebastienros** [comment]
However to be thorough we might want to run the tests also on 3.1 since there were breaking changes with ICU in 5.0.

**Comment by lahma** [comment]
Restored the netcoreapp3.1 target for tests and removed Debug mode testing in appveyor as we only ship Release mode builds.

**Review by atifaziz — APPROVED** [review]
> @atifaziz I don't think it's dropping anything. Just that the tests and benchmarks use the latest version. The library keeps the current targets.

I find the principle of not introducing unrelated changes (even if harmless) keeps reviews clear & focused, but can let it pass if it's acceptable here.

**Pull request merged**
