### PR TITLE
Decorators support

### LINKED ISSUE #255: Work on Decorators
As Ddecorators are now also in Stage 3, and landed in the ES-Tree spec:

https://github.com/estree/estree/blob/master/stage3/decorators.md

Should I implement them in Esprima-next? Is it planed to add them here? Or does anyone already work on them? (So we again nearly share the same implemntation)

### PR DESCRIPTION
**Pull request by Xicy**
Implemented Decorator

1. [Estree decorator](https://github.com/estree/estree/blob/master/stage3/decorators.md) implemented 
2. Some test cases taken from babel test cases. [decorators](https://github.com/babel/babel/tree/main/packages/babel-parser/test/fixtures/experimental/decorators) [decorators-2](https://github.com/babel/babel/tree/main/packages/babel-parser/test/fixtures/experimental/decorators-2)
3. Some strict mode test case does not pass in tests. It is not relevant to decorator.

Fixes #255

### CODE REVIEW

**Comment by lahma** [comment]
So this didn't take long 🙂 

/cc @jogibear9988 I think .NET side got there first..

**Review by lahma — APPROVED** [review]
Great work again! I'm pulling this in as were slightly stepping on each others toes, easier to rebase when no concurrent work happening. If something requires more fine-tuning I'm sure more PRs are to come 🚀

**Comment by jogibear9988** [comment]
Oh 😂
I started work on this yesterday, but I only created the properties, so now I can copy this 👍
great work

**Comment by jogibear9988** [comment]
I'm currently converting this to esprima-next.

@Xicy 
Can you tell my why this was added:
https://github.com/sebastienros/esprima-dotnet/pull/259/commits/71a117734a3c16b525844b4f500348c6f38ce727#diff-92a67081d35facbe8921de0638d8eccd7f7204c8b99a656abc3af2ea750857c1R1074

**Comment by Xicy** [comment]
> @Xicy Can you tell my why this was added: [71a1177#diff-92a67081d35facbe8921de0638d8eccd7f7204c8b99a656abc3af2ea750857c1R1074](https://github.com/sebastienros/esprima-dotnet/commit/71a117734a3c16b525844b4f500348c6f38ce727#diff-92a67081d35facbe8921de0638d8eccd7f7204c8b99a656abc3af2ea750857c1R1074)

It was about test cases, parser does not parse the methods inside of the objects. Object element waits to separated by the comma but methods does not required to add comma.

[decorator-member-expr-decorator-member-expr.js](https://github.com/tc39/test262/blob/53d6cd6d463df461e1c506e0d2be4e36de0ef6fa/test/language/expressions/class/decorator/syntax/valid/decorator-member-expr-decorator-member-expr.js#L30-L39)

**Comment by jogibear9988** [comment]
@Xicy @lahma 
ParseDecorators now allways creates a ArrayList, maybe we should only create one if a "@" is found,.

**Comment by Xicy** [comment]
> @Xicy @lahma
> ParseDecorators now allways creates a ArrayList, maybe we should only create one if a "@" is found,.

Do we have to consider the snapshot tests ? 

Because I faced an issue. All astparsers (in astexplorer.net) that support parsing decorators, append the empty array list in json file. I try to protect that requirements If Node doest not has any decorators I tried to add empty ArrayList.

If we can update snapshots and Its does not matter is it null or empty array or does not exists decorators key, I can update with nullable types. 

And then I can remove the condition also below block.
```csharp
if (accessorProperty.Decorators.Count > 0)
{
    Member("decorators", accessorProperty.Decorators);
}
```

**Comment by jogibear9988** [comment]
> Because I faced an issue. All astparsers (in astexplorer.net) that support parsing decorators, append the empty array list in json file. I try to protect that requirements If Node doest not has any decorators I tried to add empty ArrayList.


sure?

**Comment by Xicy** [comment]
> > Because I faced an issue. All astparsers (in astexplorer.net) that support parsing decorators, append the empty array list in json file. I try to protect that requirements If Node doest not has any decorators I tried to add empty ArrayList.
> 
> sure? Bildschirmfoto 2022-06-06 um 19 34 12

Sorry about that, its my bad. 
But As I said we can update as nullable type and null approach. It's ok to me.

**Comment by adams85** [comment]
> Do we have to consider the snapshot tests ?
>
> Because I faced an issue. 

This might be of interest to you: https://github.com/sebastienros/esprima-dotnet/pull/257#issuecomment-1148006877

**Pull request merged**
