### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by adams85**
Some more polishing.

### CODE REVIEW

**Review by lahma — APPROVED** [review]
LGTM 👍🏻

**Comment by adams85** [comment]
Thanks for the quick review!

I had doubts about https://github.com/sebastienros/esprima-dotnet/pull/390/commits/22b6471c6d8b5147550b1b7c15650262d83eaa87, so did some research about exactly how .NET deals with string constants. 

The pre-generated version would result in `ldstr` operations, which works like [this](https://stackoverflow.com/a/31088610/8656352) under the hood. Not quite what I hoped for... So I'd rather drop this change because it'd just increase the assembly size by 3 kB without a real benefit.

**Comment by adams85** [comment]
I believe the time will be ripe for a new RC (hopefully the last one before the final 3.x). If you agree, would you do the honors, please? :)

**Comment by lahma** [comment]
[3.0.0-rc-03](https://www.nuget.org/packages/Esprima/3.0.0-rc-03) published! 🚀

**Pull request merged**
